
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 02 19:29:09 GMT-06:00 2025
//----------------------------------------------------

package micompiladorvpr.parser;

import java_cup.runtime.Symbol;
import micompiladorvpr.asm_compiler.GeneradorEnsamblador;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Dec 02 19:29:09 GMT-06:00 2025
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\004\000\002\002\011\000\002\002" +
    "\010\000\002\002\011\000\002\004\004\000\002\004\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\007\000\002\003\007\000\002\003\007\000\002\003" +
    "\007\000\002\003\007\000\002\003\004\000\002\003\006" +
    "\000\002\003\005\000\002\003\004\000\002\003\004\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\003\000\002\006" +
    "\003\000\002\005\005\000\002\005\007\000\002\005\007" +
    "\000\002\005\007\000\002\005\007\000\002\005\007\000" +
    "\002\016\005\000\002\007\011\000\002\017\002\000\002" +
    "\007\016\000\002\020\002\000\002\010\012\000\002\021" +
    "\002\000\002\011\014\000\002\012\020\000\002\022\002" +
    "\000\002\013\012\000\002\014\011\000\002\014\007\000" +
    "\002\014\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\252\000\010\006\004\013\005\021\006\001\002\000" +
    "\004\021\247\001\002\000\004\021\241\001\002\000\004" +
    "\045\011\001\002\000\004\002\010\001\002\000\004\002" +
    "\001\001\002\000\004\046\012\001\002\000\004\047\013" +
    "\001\002\000\044\006\014\007\031\010\042\011\033\012" +
    "\022\014\034\016\036\017\043\020\015\022\023\023\035" +
    "\026\024\027\040\030\017\031\037\032\041\063\025\001" +
    "\002\000\004\063\234\001\002\000\004\045\217\001\002" +
    "\000\046\006\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7\014" +
    "\ufff7\016\ufff7\017\ufff7\020\ufff7\022\ufff7\023\ufff7\026\ufff7" +
    "\027\ufff7\030\ufff7\031\ufff7\032\ufff7\050\ufff7\063\ufff7\001" +
    "\002\000\004\045\210\001\002\000\046\006\ufffc\007\ufffc" +
    "\010\ufffc\011\ufffc\012\ufffc\014\ufffc\016\ufffc\017\ufffc\020" +
    "\ufffc\022\ufffc\023\ufffc\026\ufffc\027\ufffc\030\ufffc\031\ufffc" +
    "\032\ufffc\050\ufffc\063\ufffc\001\002\000\046\006\ufffb\007" +
    "\ufffb\010\ufffb\011\ufffb\012\ufffb\014\ufffb\016\ufffb\017\ufffb" +
    "\020\ufffb\022\ufffb\023\ufffb\026\ufffb\027\ufffb\030\ufffb\031" +
    "\ufffb\032\ufffb\050\ufffb\063\ufffb\001\002\000\004\063\204" +
    "\001\002\000\004\053\203\001\002\000\004\053\202\001" +
    "\002\000\006\033\176\041\175\001\002\000\046\006\ufff6" +
    "\007\ufff6\010\ufff6\011\ufff6\012\ufff6\014\ufff6\016\ufff6\017" +
    "\ufff6\020\ufff6\022\ufff6\023\ufff6\026\ufff6\027\ufff6\030\ufff6" +
    "\031\ufff6\032\ufff6\050\ufff6\063\ufff6\001\002\000\046\006" +
    "\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa\014\ufffa\016\ufffa" +
    "\017\ufffa\020\ufffa\022\ufffa\023\ufffa\026\ufffa\027\ufffa\030" +
    "\ufffa\031\ufffa\032\ufffa\050\ufffa\063\ufffa\001\002\000\046" +
    "\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\014\ufff8\016" +
    "\ufff8\017\ufff8\020\ufff8\022\ufff8\023\ufff8\026\ufff8\027\ufff8" +
    "\030\ufff8\031\ufff8\032\ufff8\050\ufff8\063\ufff8\001\002\000" +
    "\004\063\171\001\002\000\046\006\ufff9\007\ufff9\010\ufff9" +
    "\011\ufff9\012\ufff9\014\ufff9\016\ufff9\017\ufff9\020\ufff9\022" +
    "\ufff9\023\ufff9\026\ufff9\027\ufff9\030\ufff9\031\ufff9\032\ufff9" +
    "\050\ufff9\063\ufff9\001\002\000\004\063\165\001\002\000" +
    "\004\045\152\001\002\000\004\045\127\001\002\000\004" +
    "\047\116\001\002\000\004\045\112\001\002\000\004\045" +
    "\103\001\002\000\004\053\102\001\002\000\004\063\076" +
    "\001\002\000\004\045\uffda\001\002\000\046\006\014\007" +
    "\031\010\042\011\033\012\022\014\034\016\036\017\043" +
    "\020\015\022\023\023\035\026\024\027\040\030\017\031" +
    "\037\032\041\050\046\063\025\001\002\000\046\006\ufffd" +
    "\007\ufffd\010\ufffd\011\ufffd\012\ufffd\014\ufffd\016\ufffd\017" +
    "\ufffd\020\ufffd\022\ufffd\023\ufffd\026\ufffd\027\ufffd\030\ufffd" +
    "\031\ufffd\032\ufffd\050\ufffd\063\ufffd\001\002\000\004\002" +
    "\uffff\001\002\000\004\045\050\001\002\000\010\045\052" +
    "\063\055\064\051\001\002\000\020\034\uffe5\035\uffe5\036" +
    "\uffe5\037\uffe5\042\uffe5\046\uffe5\053\uffe5\001\002\000\010" +
    "\045\052\063\055\064\051\001\002\000\004\046\070\001" +
    "\002\000\014\034\061\035\060\036\062\037\056\042\057" +
    "\001\002\000\020\034\uffe6\035\uffe6\036\uffe6\037\uffe6\042" +
    "\uffe6\046\uffe6\053\uffe6\001\002\000\010\045\052\063\055" +
    "\064\051\001\002\000\010\045\052\063\055\064\051\001" +
    "\002\000\010\045\052\063\055\064\051\001\002\000\010" +
    "\045\052\063\055\064\051\001\002\000\010\045\052\063" +
    "\055\064\051\001\002\000\020\034\uffe9\035\uffe9\036\uffe9" +
    "\037\uffe9\042\uffe9\046\uffe9\053\uffe9\001\002\000\020\034" +
    "\uffeb\035\uffeb\036\062\037\056\042\uffeb\046\uffeb\053\uffeb" +
    "\001\002\000\020\034\uffea\035\uffea\036\062\037\056\042" +
    "\uffea\046\uffea\053\uffea\001\002\000\016\034\061\035\060" +
    "\036\062\037\056\046\uffde\053\uffde\001\002\000\020\034" +
    "\uffe8\035\uffe8\036\uffe8\037\uffe8\042\uffe8\046\uffe8\053\uffe8" +
    "\001\002\000\004\047\071\001\002\000\044\006\014\007" +
    "\031\010\042\011\033\012\022\014\034\016\036\017\043" +
    "\020\015\022\023\023\035\026\024\027\040\030\017\031" +
    "\037\032\041\063\025\001\002\000\046\006\014\007\031" +
    "\010\042\011\033\012\022\014\034\016\036\017\043\020" +
    "\015\022\023\023\035\026\024\027\040\030\017\031\037" +
    "\032\041\050\073\063\025\001\002\000\046\006\uffd9\007" +
    "\uffd9\010\uffd9\011\uffd9\012\uffd9\014\uffd9\016\uffd9\017\uffd9" +
    "\020\uffd9\022\uffd9\023\uffd9\026\uffd9\027\uffd9\030\uffd9\031" +
    "\uffd9\032\uffd9\050\uffd9\063\uffd9\001\002\000\014\034\061" +
    "\035\060\036\062\037\056\046\075\001\002\000\020\034" +
    "\uffe7\035\uffe7\036\uffe7\037\uffe7\042\uffe7\046\uffe7\053\uffe7" +
    "\001\002\000\004\033\077\001\002\000\004\065\100\001" +
    "\002\000\004\053\101\001\002\000\046\006\uffe2\007\uffe2" +
    "\010\uffe2\011\uffe2\012\uffe2\014\uffe2\016\uffe2\017\uffe2\020" +
    "\uffe2\022\uffe2\023\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2" +
    "\032\uffe2\050\uffe2\063\uffe2\001\002\000\046\006\ufff0\007" +
    "\ufff0\010\ufff0\011\ufff0\012\ufff0\014\ufff0\016\ufff0\017\ufff0" +
    "\020\ufff0\022\ufff0\023\ufff0\026\ufff0\027\ufff0\030\ufff0\031" +
    "\ufff0\032\ufff0\050\ufff0\063\ufff0\001\002\000\006\063\105" +
    "\065\104\001\002\000\004\046\110\001\002\000\004\046" +
    "\106\001\002\000\004\053\107\001\002\000\046\006\ufff5" +
    "\007\ufff5\010\ufff5\011\ufff5\012\ufff5\014\ufff5\016\ufff5\017" +
    "\ufff5\020\ufff5\022\ufff5\023\ufff5\026\ufff5\027\ufff5\030\ufff5" +
    "\031\ufff5\032\ufff5\050\ufff5\063\ufff5\001\002\000\004\053" +
    "\111\001\002\000\046\006\ufff4\007\ufff4\010\ufff4\011\ufff4" +
    "\012\ufff4\014\ufff4\016\ufff4\017\ufff4\020\ufff4\022\ufff4\023" +
    "\ufff4\026\ufff4\027\ufff4\030\ufff4\031\ufff4\032\ufff4\050\ufff4" +
    "\063\ufff4\001\002\000\004\063\113\001\002\000\004\046" +
    "\114\001\002\000\004\053\115\001\002\000\046\006\ufff1" +
    "\007\ufff1\010\ufff1\011\ufff1\012\ufff1\014\ufff1\016\ufff1\017" +
    "\ufff1\020\ufff1\022\ufff1\023\ufff1\026\ufff1\027\ufff1\030\ufff1" +
    "\031\ufff1\032\ufff1\050\ufff1\063\ufff1\001\002\000\044\006" +
    "\uffd8\007\uffd8\010\uffd8\011\uffd8\012\uffd8\014\uffd8\016\uffd8" +
    "\017\uffd8\020\uffd8\022\uffd8\023\uffd8\026\uffd8\027\uffd8\030" +
    "\uffd8\031\uffd8\032\uffd8\063\uffd8\001\002\000\044\006\014" +
    "\007\031\010\042\011\033\012\022\014\034\016\036\017" +
    "\043\020\015\022\023\023\035\026\024\027\040\030\017" +
    "\031\037\032\041\063\025\001\002\000\046\006\014\007" +
    "\031\010\042\011\033\012\022\014\034\016\036\017\043" +
    "\020\015\022\023\023\035\026\024\027\040\030\017\031" +
    "\037\032\041\050\121\063\025\001\002\000\004\017\122" +
    "\001\002\000\004\045\123\001\002\000\010\045\052\063" +
    "\055\064\051\001\002\000\004\046\125\001\002\000\004" +
    "\053\126\001\002\000\046\006\uffd7\007\uffd7\010\uffd7\011" +
    "\uffd7\012\uffd7\014\uffd7\016\uffd7\017\uffd7\020\uffd7\022\uffd7" +
    "\023\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7\032\uffd7\050" +
    "\uffd7\063\uffd7\001\002\000\004\063\130\001\002\000\004" +
    "\046\131\001\002\000\004\047\132\001\002\000\010\024" +
    "\uffd5\025\uffd5\050\uffd5\001\002\000\010\024\136\025\135" +
    "\050\uffd1\001\002\000\004\050\151\001\002\000\004\054" +
    "\145\001\002\000\004\064\137\001\002\000\004\054\140" +
    "\001\002\000\044\006\014\007\031\010\042\011\033\012" +
    "\022\014\034\016\036\017\043\020\015\022\023\023\035" +
    "\026\024\027\040\030\017\031\037\032\041\063\025\001" +
    "\002\000\044\006\014\007\031\010\042\011\033\012\022" +
    "\014\034\016\036\017\043\020\015\022\023\023\035\026" +
    "\142\027\040\030\017\031\037\032\041\063\025\001\002" +
    "\000\004\053\143\001\002\000\052\006\uffed\007\uffed\010" +
    "\uffed\011\uffed\012\uffed\014\uffed\016\uffed\017\uffed\020\uffed" +
    "\022\uffed\023\uffed\024\136\025\135\026\uffed\027\uffed\030" +
    "\uffed\031\uffed\032\uffed\050\uffd1\063\uffed\001\002\000\004" +
    "\050\uffd3\001\002\000\044\006\014\007\031\010\042\011" +
    "\033\012\022\014\034\016\036\017\043\020\015\022\023" +
    "\023\035\026\024\027\040\030\017\031\037\032\041\063" +
    "\025\001\002\000\044\006\014\007\031\010\042\011\033" +
    "\012\022\014\034\016\036\017\043\020\015\022\023\023" +
    "\035\026\147\027\040\030\017\031\037\032\041\063\025" +
    "\001\002\000\004\053\150\001\002\000\046\006\uffed\007" +
    "\uffed\010\uffed\011\uffed\012\uffed\014\uffed\016\uffed\017\uffed" +
    "\020\uffed\022\uffed\023\uffed\026\uffed\027\uffed\030\uffed\031" +
    "\uffed\032\uffed\050\uffd2\063\uffed\001\002\000\046\006\uffd4" +
    "\007\uffd4\010\uffd4\011\uffd4\012\uffd4\014\uffd4\016\uffd4\017" +
    "\uffd4\020\uffd4\022\uffd4\023\uffd4\026\uffd4\027\uffd4\030\uffd4" +
    "\031\uffd4\032\uffd4\050\uffd4\063\uffd4\001\002\000\010\045" +
    "\052\063\055\064\051\001\002\000\004\046\154\001\002" +
    "\000\004\047\155\001\002\000\044\006\014\007\031\010" +
    "\042\011\033\012\022\014\034\016\036\017\043\020\015" +
    "\022\023\023\035\026\024\027\040\030\017\031\037\032" +
    "\041\063\025\001\002\000\046\006\014\007\031\010\042" +
    "\011\033\012\022\014\034\016\036\017\043\020\015\022" +
    "\023\023\035\026\024\027\040\030\017\031\037\032\041" +
    "\050\157\063\025\001\002\000\050\006\uffdd\007\uffdd\010" +
    "\uffdd\011\uffdd\012\uffdd\014\uffdd\015\160\016\uffdd\017\uffdd" +
    "\020\uffdd\022\uffdd\023\uffdd\026\uffdd\027\uffdd\030\uffdd\031" +
    "\uffdd\032\uffdd\050\uffdd\063\uffdd\001\002\000\004\047\uffdc" +
    "\001\002\000\004\047\162\001\002\000\044\006\014\007" +
    "\031\010\042\011\033\012\022\014\034\016\036\017\043" +
    "\020\015\022\023\023\035\026\024\027\040\030\017\031" +
    "\037\032\041\063\025\001\002\000\046\006\014\007\031" +
    "\010\042\011\033\012\022\014\034\016\036\017\043\020" +
    "\015\022\023\023\035\026\024\027\040\030\017\031\037" +
    "\032\041\050\164\063\025\001\002\000\046\006\uffdb\007" +
    "\uffdb\010\uffdb\011\uffdb\012\uffdb\014\uffdb\016\uffdb\017\uffdb" +
    "\020\uffdb\022\uffdb\023\uffdb\026\uffdb\027\uffdb\030\uffdb\031" +
    "\uffdb\032\uffdb\050\uffdb\063\uffdb\001\002\000\004\033\166" +
    "\001\002\000\004\065\167\001\002\000\004\053\170\001" +
    "\002\000\046\006\uffe0\007\uffe0\010\uffe0\011\uffe0\012\uffe0" +
    "\014\uffe0\016\uffe0\017\uffe0\020\uffe0\022\uffe0\023\uffe0\026" +
    "\uffe0\027\uffe0\030\uffe0\031\uffe0\032\uffe0\050\uffe0\063\uffe0" +
    "\001\002\000\004\033\172\001\002\000\004\064\173\001" +
    "\002\000\004\053\174\001\002\000\046\006\uffe1\007\uffe1" +
    "\010\uffe1\011\uffe1\012\uffe1\014\uffe1\016\uffe1\017\uffe1\020" +
    "\uffe1\022\uffe1\023\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1" +
    "\032\uffe1\050\uffe1\063\uffe1\001\002\000\004\053\201\001" +
    "\002\000\010\045\052\063\055\064\051\001\002\000\014" +
    "\034\061\035\060\036\062\037\056\053\200\001\002\000" +
    "\046\006\uffef\007\uffef\010\uffef\011\uffef\012\uffef\014\uffef" +
    "\016\uffef\017\uffef\020\uffef\022\uffef\023\uffef\026\uffef\027" +
    "\uffef\030\uffef\031\uffef\032\uffef\050\uffef\063\uffef\001\002" +
    "\000\046\006\uffee\007\uffee\010\uffee\011\uffee\012\uffee\014" +
    "\uffee\016\uffee\017\uffee\020\uffee\022\uffee\023\uffee\026\uffee" +
    "\027\uffee\030\uffee\031\uffee\032\uffee\050\uffee\063\uffee\001" +
    "\002\000\046\006\uffed\007\uffed\010\uffed\011\uffed\012\uffed" +
    "\014\uffed\016\uffed\017\uffed\020\uffed\022\uffed\023\uffed\026" +
    "\uffed\027\uffed\030\uffed\031\uffed\032\uffed\050\uffed\063\uffed" +
    "\001\002\000\046\006\uffec\007\uffec\010\uffec\011\uffec\012" +
    "\uffec\014\uffec\016\uffec\017\uffec\020\uffec\022\uffec\023\uffec" +
    "\026\uffec\027\uffec\030\uffec\031\uffec\032\uffec\050\uffec\063" +
    "\uffec\001\002\000\004\033\205\001\002\000\004\044\206" +
    "\001\002\000\004\053\207\001\002\000\046\006\uffdf\007" +
    "\uffdf\010\uffdf\011\uffdf\012\uffdf\014\uffdf\016\uffdf\017\uffdf" +
    "\020\uffdf\022\uffdf\023\uffdf\026\uffdf\027\uffdf\030\uffdf\031" +
    "\uffdf\032\uffdf\050\uffdf\063\uffdf\001\002\000\006\063\212" +
    "\065\211\001\002\000\004\046\215\001\002\000\004\046" +
    "\213\001\002\000\004\053\214\001\002\000\046\006\ufff3" +
    "\007\ufff3\010\ufff3\011\ufff3\012\ufff3\014\ufff3\016\ufff3\017" +
    "\ufff3\020\ufff3\022\ufff3\023\ufff3\026\ufff3\027\ufff3\030\ufff3" +
    "\031\ufff3\032\ufff3\050\ufff3\063\ufff3\001\002\000\004\053" +
    "\216\001\002\000\046\006\ufff2\007\ufff2\010\ufff2\011\ufff2" +
    "\012\ufff2\014\ufff2\016\ufff2\017\ufff2\020\ufff2\022\ufff2\023" +
    "\ufff2\026\ufff2\027\ufff2\030\ufff2\031\ufff2\032\ufff2\050\ufff2" +
    "\063\ufff2\001\002\000\004\063\220\001\002\000\004\033" +
    "\221\001\002\000\004\064\222\001\002\000\004\053\223" +
    "\001\002\000\010\045\052\063\055\064\051\001\002\000" +
    "\004\053\225\001\002\000\004\063\226\001\002\000\004" +
    "\041\227\001\002\000\004\046\230\001\002\000\004\047" +
    "\231\001\002\000\044\006\014\007\031\010\042\011\033" +
    "\012\022\014\034\016\036\017\043\020\015\022\023\023" +
    "\035\026\024\027\040\030\017\031\037\032\041\063\025" +
    "\001\002\000\046\006\014\007\031\010\042\011\033\012" +
    "\022\014\034\016\036\017\043\020\015\022\023\023\035" +
    "\026\024\027\040\030\017\031\037\032\041\050\233\063" +
    "\025\001\002\000\046\006\uffd6\007\uffd6\010\uffd6\011\uffd6" +
    "\012\uffd6\014\uffd6\016\uffd6\017\uffd6\020\uffd6\022\uffd6\023" +
    "\uffd6\026\uffd6\027\uffd6\030\uffd6\031\uffd6\032\uffd6\050\uffd6" +
    "\063\uffd6\001\002\000\006\033\236\053\235\001\002\000" +
    "\046\006\uffe4\007\uffe4\010\uffe4\011\uffe4\012\uffe4\014\uffe4" +
    "\016\uffe4\017\uffe4\020\uffe4\022\uffe4\023\uffe4\026\uffe4\027" +
    "\uffe4\030\uffe4\031\uffe4\032\uffe4\050\uffe4\063\uffe4\001\002" +
    "\000\010\045\052\063\055\064\051\001\002\000\014\034" +
    "\061\035\060\036\062\037\056\053\240\001\002\000\046" +
    "\006\uffe3\007\uffe3\010\uffe3\011\uffe3\012\uffe3\014\uffe3\016" +
    "\uffe3\017\uffe3\020\uffe3\022\uffe3\023\uffe3\026\uffe3\027\uffe3" +
    "\030\uffe3\031\uffe3\032\uffe3\050\uffe3\063\uffe3\001\002\000" +
    "\004\045\242\001\002\000\004\046\243\001\002\000\004" +
    "\047\244\001\002\000\044\006\014\007\031\010\042\011" +
    "\033\012\022\014\034\016\036\017\043\020\015\022\023" +
    "\023\035\026\024\027\040\030\017\031\037\032\041\063" +
    "\025\001\002\000\046\006\014\007\031\010\042\011\033" +
    "\012\022\014\034\016\036\017\043\020\015\022\023\023" +
    "\035\026\024\027\040\030\017\031\037\032\041\050\246" +
    "\063\025\001\002\000\004\002\ufffe\001\002\000\004\045" +
    "\250\001\002\000\004\046\251\001\002\000\004\047\252" +
    "\001\002\000\044\006\014\007\031\010\042\011\033\012" +
    "\022\014\034\016\036\017\043\020\015\022\023\023\035" +
    "\026\024\027\040\030\017\031\037\032\041\063\025\001" +
    "\002\000\046\006\014\007\031\010\042\011\033\012\022" +
    "\014\034\016\036\017\043\020\015\022\023\023\035\026" +
    "\024\027\040\030\017\031\037\032\041\050\254\063\025" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\252\000\004\002\006\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\017\004\043\005\020\007\026\010\031\011\027\012\015" +
    "\013\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\020\046\001\001\000\020" +
    "\003\044\005\020\007\026\010\031\011\027\012\015\013" +
    "\025\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\053\016\052\001\001\000\002\001" +
    "\001\000\004\006\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\066\001\001\000" +
    "\004\006\065\001\001\000\004\006\064\001\001\000\004" +
    "\006\063\001\001\000\004\006\062\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\003\017\004" +
    "\071\005\020\007\026\010\031\011\027\012\015\013\025" +
    "\001\001\000\020\003\044\005\020\007\026\010\031\011" +
    "\027\012\015\013\025\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\116\001\001\000\022" +
    "\003\017\004\117\005\020\007\026\010\031\011\027\012" +
    "\015\013\025\001\001\000\020\003\044\005\020\007\026" +
    "\010\031\011\027\012\015\013\025\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\006\053\016\123\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\132\001\001\000\004\014\133\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\003\017\004\140\005\020\007\026\010\031\011" +
    "\027\012\015\013\025\001\001\000\020\003\044\005\020" +
    "\007\026\010\031\011\027\012\015\013\025\001\001\000" +
    "\002\001\001\000\004\014\143\001\001\000\002\001\001" +
    "\000\022\003\017\004\145\005\020\007\026\010\031\011" +
    "\027\012\015\013\025\001\001\000\020\003\044\005\020" +
    "\007\026\010\031\011\027\012\015\013\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\053\016\152\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\003\017\004\155\005\020\007\026\010\031" +
    "\011\027\012\015\013\025\001\001\000\020\003\044\005" +
    "\020\007\026\010\031\011\027\012\015\013\025\001\001" +
    "\000\002\001\001\000\004\017\160\001\001\000\002\001" +
    "\001\000\022\003\017\004\162\005\020\007\026\010\031" +
    "\011\027\012\015\013\025\001\001\000\020\003\044\005" +
    "\020\007\026\010\031\011\027\012\015\013\025\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\176\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\053" +
    "\016\223\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\003\017\004\231\005\020\007\026\010\031\011\027\012" +
    "\015\013\025\001\001\000\020\003\044\005\020\007\026" +
    "\010\031\011\027\012\015\013\025\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\236" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\003\017" +
    "\004\244\005\020\007\026\010\031\011\027\012\015\013" +
    "\025\001\001\000\020\003\044\005\020\007\026\010\031" +
    "\011\027\012\015\013\025\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\003\017\004\252\005\020\007\026\010\031\011\027\012" +
    "\015\013\025\001\001\000\020\003\044\005\020\007\026" +
    "\010\031\011\027\012\015\013\025\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    public void syntax_error(Symbol s){ this.s = s; }
    public Symbol getS(){ return this.s; }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // LISTA_CASOS ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_CASOS",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // LISTA_CASOS ::= Default Dos_puntos LISTA_SENTENCIAS Break P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_CASOS",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // LISTA_CASOS ::= Case Numero Dos_puntos LISTA_SENTENCIAS Break P_coma LISTA_CASOS 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_CASOS",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // SENTENCIA_SWITCH ::= Switch Parentesis_a Identificador Parentesis_c Llave_a NT$3 LISTA_CASOS Llave_c 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.terminarSwitch(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SWITCH",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // NT$3 ::= 
            {
              Object RESULT =null;
 GeneradorEnsamblador.instancia.iniciarSwitch(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$3",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // SENTENCIA_FOR ::= For Parentesis_a Identificador Igual Numero P_coma CONDICION P_coma Identificador Op_incremento Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_FOR",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-13)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // SENTENCIA_DO_WHILE ::= Do Llave_a NT$2 LISTA_SENTENCIAS Llave_c While Parentesis_a CONDICION Parentesis_c P_coma 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).value;
		 GeneradorEnsamblador.instancia.terminarDo(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_DO_WHILE",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-9)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$2 ::= 
            {
              Object RESULT =null;
 GeneradorEnsamblador.instancia.iniciarDo(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$2",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // SENTENCIA_WHILE ::= While NT$1 Parentesis_a CONDICION Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).value;
		 GeneradorEnsamblador.instancia.terminarWhile(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_WHILE",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // NT$1 ::= 
            {
              Object RESULT =null;
 GeneradorEnsamblador.instancia.iniciarWhile(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$1",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // SENTENCIA_IF ::= If Parentesis_a CONDICION Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c Else NT$0 Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		 GeneradorEnsamblador.instancia.finIf(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-11)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // NT$0 ::= 
            {
              Object RESULT =null;
 GeneradorEnsamblador.instancia.elseIf(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$0",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // SENTENCIA_IF ::= If Parentesis_a CONDICION Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.finIf(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // CONDICION ::= EXPRESION_A Op_relacional EXPRESION_A 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.comparacion((String)op); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // DECLARACION ::= T_bool Identificador Igual Op_booleano P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararBool(id, (String)val); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // DECLARACION ::= T_char Identificador Igual Texto P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararChar(id, val); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // DECLARACION ::= T_float Identificador Igual Numero P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararFloat(id, val); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // DECLARACION ::= T_string Identificador Igual Texto P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararCadena(id, val); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // DECLARACION ::= T_int Identificador Igual EXPRESION_A P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		 GeneradorEnsamblador.instancia.declararVariable(id); GeneradorEnsamblador.instancia.asignarDesdePila(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // DECLARACION ::= T_int Identificador P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararVariable(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EXPRESION_A ::= Numero 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 GeneradorEnsamblador.instancia.cargarValorEnPila(num); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXPRESION_A ::= Identificador 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 GeneradorEnsamblador.instancia.cargarValorEnPila(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EXPRESION_A ::= Parentesis_a EXPRESION_A Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // EXPRESION_A ::= EXPRESION_A Division EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("/"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // EXPRESION_A ::= EXPRESION_A Multiplicacion EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("*"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXPRESION_A ::= EXPRESION_A Resta EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("-"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXPRESION_A ::= EXPRESION_A Suma EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("+"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // SENTENCIA ::= Retorno P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SENTENCIA ::= Break P_coma 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.generarBreak(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // SENTENCIA ::= Identificador Op_incremento P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.incrementarVariable(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SENTENCIA ::= Identificador Igual EXPRESION_A P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		 GeneradorEnsamblador.instancia.asignarDesdePila(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SENTENCIA ::= Limpia P_coma 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.generarClrscr(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SENTENCIA ::= Lectura Parentesis_a Identificador Parentesis_c P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.leerVariable(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= ImprimeLn Parentesis_a Texto Parentesis_c P_coma 
            {
              Object RESULT =null;
		int txtleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int txtright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String txt = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.imprimirVariableLn(txt); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= ImprimeLn Parentesis_a Identificador Parentesis_c P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.imprimirVariableLn(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= Imprime Parentesis_a Texto Parentesis_c P_coma 
            {
              Object RESULT =null;
		int txtleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int txtright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String txt = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.imprimirVariable(txt); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= Imprime Parentesis_a Identificador Parentesis_c P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.imprimirVariable(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= SENTENCIA_SWITCH 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= SENTENCIA_FOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= SENTENCIA_DO_WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= SENTENCIA_WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= SENTENCIA_IF 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LISTA_SENTENCIAS ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= T_void Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= T_int Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

