
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 02 16:04:09 GMT-06:00 2025
//----------------------------------------------------

package micompiladorvpr.parser;

import java_cup.runtime.Symbol;
import micompiladorvpr.asm_compiler.GeneradorEnsamblador;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Dec 02 16:04:09 GMT-06:00 2025
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\002\004\000\002\002\011\000\002\002" +
    "\010\000\002\002\011\000\002\004\004\000\002\004\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\007\000\002" +
    "\005\006\000\002\005\004\000\002\005\004\000\002\005" +
    "\004\000\002\007\005\000\002\007\005\000\002\007\005" +
    "\000\002\007\005\000\002\007\005\000\002\007\003\000" +
    "\002\007\003\000\002\006\005\000\002\006\007\000\002" +
    "\006\007\000\002\006\005\000\002\010\011\000\002\010" +
    "\015\000\002\011\011\000\002\012\013\000\002\013\020" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\010\006\004\013\005\025\006\001\002\000" +
    "\004\025\156\001\002\000\004\025\150\001\002\000\004" +
    "\054\011\001\002\000\004\002\010\001\002\000\004\002" +
    "\001\001\002\000\004\055\012\001\002\000\004\056\013" +
    "\001\002\000\032\006\014\007\026\010\034\014\030\016" +
    "\031\017\035\020\015\024\022\026\021\027\032\032\033" +
    "\072\023\001\002\000\004\072\143\001\002\000\004\054" +
    "\126\001\002\000\034\006\ufff7\007\ufff7\010\ufff7\014\ufff7" +
    "\016\ufff7\017\ufff7\020\ufff7\024\ufff7\026\ufff7\027\ufff7\032" +
    "\ufff7\057\ufff7\072\ufff7\001\002\000\034\006\ufffc\007\ufffc" +
    "\010\ufffc\014\ufffc\016\ufffc\017\ufffc\020\ufffc\024\ufffc\026" +
    "\ufffc\027\ufffc\032\ufffc\057\ufffc\072\ufffc\001\002\000\034" +
    "\006\ufffb\007\ufffb\010\ufffb\014\ufffb\016\ufffb\017\ufffb\020" +
    "\ufffb\024\ufffb\026\ufffb\027\ufffb\032\ufffb\057\ufffb\072\ufffb" +
    "\001\002\000\004\062\125\001\002\000\004\062\124\001" +
    "\002\000\004\040\121\001\002\000\034\006\ufffa\007\ufffa" +
    "\010\ufffa\014\ufffa\016\ufffa\017\ufffa\020\ufffa\024\ufffa\026" +
    "\ufffa\027\ufffa\032\ufffa\057\ufffa\072\ufffa\001\002\000\034" +
    "\006\ufff8\007\ufff8\010\ufff8\014\ufff8\016\ufff8\017\ufff8\020" +
    "\ufff8\024\ufff8\026\ufff8\027\ufff8\032\ufff8\057\ufff8\072\ufff8" +
    "\001\002\000\004\072\117\001\002\000\034\006\ufff9\007" +
    "\ufff9\010\ufff9\014\ufff9\016\ufff9\017\ufff9\020\ufff9\024\ufff9" +
    "\026\ufff9\027\ufff9\032\ufff9\057\ufff9\072\ufff9\001\002\000" +
    "\004\054\105\001\002\000\004\056\075\001\002\000\004" +
    "\054\071\001\002\000\004\062\070\001\002\000\004\072" +
    "\064\001\002\000\004\054\041\001\002\000\034\006\014" +
    "\007\026\010\034\014\030\016\031\017\035\020\015\024" +
    "\022\026\021\027\032\032\033\057\040\072\023\001\002" +
    "\000\034\006\ufffd\007\ufffd\010\ufffd\014\ufffd\016\ufffd\017" +
    "\ufffd\020\ufffd\024\ufffd\026\ufffd\027\ufffd\032\ufffd\057\ufffd" +
    "\072\ufffd\001\002\000\004\002\uffff\001\002\000\010\054" +
    "\043\072\045\073\042\001\002\000\016\041\uffeb\042\uffeb" +
    "\043\uffeb\044\uffeb\055\uffeb\062\uffeb\001\002\000\010\054" +
    "\043\072\045\073\042\001\002\000\014\041\050\042\047" +
    "\043\051\044\046\055\052\001\002\000\016\041\uffec\042" +
    "\uffec\043\uffec\044\uffec\055\uffec\062\uffec\001\002\000\010" +
    "\054\043\072\045\073\042\001\002\000\010\054\043\072" +
    "\045\073\042\001\002\000\010\054\043\072\045\073\042" +
    "\001\002\000\010\054\043\072\045\073\042\001\002\000" +
    "\004\056\053\001\002\000\032\006\014\007\026\010\034" +
    "\014\030\016\031\017\035\020\015\024\022\026\021\027" +
    "\032\032\033\072\023\001\002\000\034\006\014\007\026" +
    "\010\034\014\030\016\031\017\035\020\015\024\022\026" +
    "\021\027\032\032\033\057\055\072\023\001\002\000\034" +
    "\006\uffe4\007\uffe4\010\uffe4\014\uffe4\016\uffe4\017\uffe4\020" +
    "\uffe4\024\uffe4\026\uffe4\027\uffe4\032\uffe4\057\uffe4\072\uffe4" +
    "\001\002\000\016\041\uffef\042\uffef\043\uffef\044\uffef\055" +
    "\uffef\062\uffef\001\002\000\016\041\ufff1\042\ufff1\043\051" +
    "\044\046\055\ufff1\062\ufff1\001\002\000\016\041\ufff0\042" +
    "\ufff0\043\051\044\046\055\ufff0\062\ufff0\001\002\000\016" +
    "\041\uffee\042\uffee\043\uffee\044\uffee\055\uffee\062\uffee\001" +
    "\002\000\014\041\050\042\047\043\051\044\046\055\063" +
    "\001\002\000\016\041\uffed\042\uffed\043\uffed\044\uffed\055" +
    "\uffed\062\uffed\001\002\000\004\040\065\001\002\000\004" +
    "\074\066\001\002\000\004\062\067\001\002\000\034\006" +
    "\uffe8\007\uffe8\010\uffe8\014\uffe8\016\uffe8\017\uffe8\020\uffe8" +
    "\024\uffe8\026\uffe8\027\uffe8\032\uffe8\057\uffe8\072\uffe8\001" +
    "\002\000\034\006\ufff4\007\ufff4\010\ufff4\014\ufff4\016\ufff4" +
    "\017\ufff4\020\ufff4\024\ufff4\026\ufff4\027\ufff4\032\ufff4\057" +
    "\ufff4\072\ufff4\001\002\000\004\072\072\001\002\000\004" +
    "\055\073\001\002\000\004\062\074\001\002\000\034\006" +
    "\ufff6\007\ufff6\010\ufff6\014\ufff6\016\ufff6\017\ufff6\020\ufff6" +
    "\024\ufff6\026\ufff6\027\ufff6\032\ufff6\057\ufff6\072\ufff6\001" +
    "\002\000\032\006\014\007\026\010\034\014\030\016\031" +
    "\017\035\020\015\024\022\026\021\027\032\032\033\072" +
    "\023\001\002\000\034\006\014\007\026\010\034\014\030" +
    "\016\031\017\035\020\015\024\022\026\021\027\032\032" +
    "\033\057\077\072\023\001\002\000\004\017\100\001\002" +
    "\000\004\054\101\001\002\000\010\054\043\072\045\073" +
    "\042\001\002\000\014\041\050\042\047\043\051\044\046" +
    "\055\103\001\002\000\004\062\104\001\002\000\034\006" +
    "\uffe3\007\uffe3\010\uffe3\014\uffe3\016\uffe3\017\uffe3\020\uffe3" +
    "\024\uffe3\026\uffe3\027\uffe3\032\uffe3\057\uffe3\072\uffe3\001" +
    "\002\000\010\054\043\072\045\073\042\001\002\000\014" +
    "\041\050\042\047\043\051\044\046\055\107\001\002\000" +
    "\004\056\110\001\002\000\032\006\014\007\026\010\034" +
    "\014\030\016\031\017\035\020\015\024\022\026\021\027" +
    "\032\032\033\072\023\001\002\000\034\006\014\007\026" +
    "\010\034\014\030\016\031\017\035\020\015\024\022\026" +
    "\021\027\032\032\033\057\112\072\023\001\002\000\036" +
    "\006\uffe6\007\uffe6\010\uffe6\014\uffe6\015\113\016\uffe6\017" +
    "\uffe6\020\uffe6\024\uffe6\026\uffe6\027\uffe6\032\uffe6\057\uffe6" +
    "\072\uffe6\001\002\000\004\056\114\001\002\000\032\006" +
    "\014\007\026\010\034\014\030\016\031\017\035\020\015" +
    "\024\022\026\021\027\032\032\033\072\023\001\002\000" +
    "\034\006\014\007\026\010\034\014\030\016\031\017\035" +
    "\020\015\024\022\026\021\027\032\032\033\057\116\072" +
    "\023\001\002\000\034\006\uffe5\007\uffe5\010\uffe5\014\uffe5" +
    "\016\uffe5\017\uffe5\020\uffe5\024\uffe5\026\uffe5\027\uffe5\032" +
    "\uffe5\057\uffe5\072\uffe5\001\002\000\004\062\120\001\002" +
    "\000\034\006\uffe7\007\uffe7\010\uffe7\014\uffe7\016\uffe7\017" +
    "\uffe7\020\uffe7\024\uffe7\026\uffe7\027\uffe7\032\uffe7\057\uffe7" +
    "\072\uffe7\001\002\000\010\054\043\072\045\073\042\001" +
    "\002\000\014\041\050\042\047\043\051\044\046\062\123" +
    "\001\002\000\034\006\ufff5\007\ufff5\010\ufff5\014\ufff5\016" +
    "\ufff5\017\ufff5\020\ufff5\024\ufff5\026\ufff5\027\ufff5\032\ufff5" +
    "\057\ufff5\072\ufff5\001\002\000\034\006\ufff3\007\ufff3\010" +
    "\ufff3\014\ufff3\016\ufff3\017\ufff3\020\ufff3\024\ufff3\026\ufff3" +
    "\027\ufff3\032\ufff3\057\ufff3\072\ufff3\001\002\000\034\006" +
    "\ufff2\007\ufff2\010\ufff2\014\ufff2\016\ufff2\017\ufff2\020\ufff2" +
    "\024\ufff2\026\ufff2\027\ufff2\032\ufff2\057\ufff2\072\ufff2\001" +
    "\002\000\004\072\127\001\002\000\004\040\130\001\002" +
    "\000\004\073\131\001\002\000\004\062\132\001\002\000" +
    "\010\054\043\072\045\073\042\001\002\000\014\041\050" +
    "\042\047\043\051\044\046\062\134\001\002\000\004\072" +
    "\135\001\002\000\004\050\136\001\002\000\004\055\137" +
    "\001\002\000\004\056\140\001\002\000\032\006\014\007" +
    "\026\010\034\014\030\016\031\017\035\020\015\024\022" +
    "\026\021\027\032\032\033\072\023\001\002\000\034\006" +
    "\014\007\026\010\034\014\030\016\031\017\035\020\015" +
    "\024\022\026\021\027\032\032\033\057\142\072\023\001" +
    "\002\000\034\006\uffe2\007\uffe2\010\uffe2\014\uffe2\016\uffe2" +
    "\017\uffe2\020\uffe2\024\uffe2\026\uffe2\027\uffe2\032\uffe2\057" +
    "\uffe2\072\uffe2\001\002\000\006\040\145\062\144\001\002" +
    "\000\034\006\uffea\007\uffea\010\uffea\014\uffea\016\uffea\017" +
    "\uffea\020\uffea\024\uffea\026\uffea\027\uffea\032\uffea\057\uffea" +
    "\072\uffea\001\002\000\010\054\043\072\045\073\042\001" +
    "\002\000\014\041\050\042\047\043\051\044\046\062\147" +
    "\001\002\000\034\006\uffe9\007\uffe9\010\uffe9\014\uffe9\016" +
    "\uffe9\017\uffe9\020\uffe9\024\uffe9\026\uffe9\027\uffe9\032\uffe9" +
    "\057\uffe9\072\uffe9\001\002\000\004\054\151\001\002\000" +
    "\004\055\152\001\002\000\004\056\153\001\002\000\032" +
    "\006\014\007\026\010\034\014\030\016\031\017\035\020" +
    "\015\024\022\026\021\027\032\032\033\072\023\001\002" +
    "\000\034\006\014\007\026\010\034\014\030\016\031\017" +
    "\035\020\015\024\022\026\021\027\032\032\033\057\155" +
    "\072\023\001\002\000\004\002\ufffe\001\002\000\004\054" +
    "\157\001\002\000\004\055\160\001\002\000\004\056\161" +
    "\001\002\000\032\006\014\007\026\010\034\014\030\016" +
    "\031\017\035\020\015\024\022\026\021\027\032\032\033" +
    "\072\023\001\002\000\034\006\014\007\026\010\034\014" +
    "\030\016\031\017\035\020\015\024\022\026\021\027\032" +
    "\032\033\057\163\072\023\001\002\000\004\002\000\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\004\002\006\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\004" +
    "\035\005\016\006\017\010\023\011\026\012\024\013\015" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\005\036" +
    "\006\017\010\023\011\026\012\024\013\015\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\043\001\001" +
    "\000\002\001\001\000\004\007\061\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\060\001\001\000\004" +
    "\007\057\001\001\000\004\007\056\001\001\000\004\007" +
    "\055\001\001\000\002\001\001\000\020\004\053\005\016" +
    "\006\017\010\023\011\026\012\024\013\015\001\001\000" +
    "\016\005\036\006\017\010\023\011\026\012\024\013\015" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\004\075\005\016\006\017\010\023\011\026" +
    "\012\024\013\015\001\001\000\016\005\036\006\017\010" +
    "\023\011\026\012\024\013\015\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\101\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\105" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\004" +
    "\110\005\016\006\017\010\023\011\026\012\024\013\015" +
    "\001\001\000\016\005\036\006\017\010\023\011\026\012" +
    "\024\013\015\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\004\114\005\016\006\017\010\023\011\026\012" +
    "\024\013\015\001\001\000\016\005\036\006\017\010\023" +
    "\011\026\012\024\013\015\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\121\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\132\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\004\140\005\016\006" +
    "\017\010\023\011\026\012\024\013\015\001\001\000\016" +
    "\005\036\006\017\010\023\011\026\012\024\013\015\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\145\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\004\153\005\016\006\017\010\023\011\026\012" +
    "\024\013\015\001\001\000\016\005\036\006\017\010\023" +
    "\011\026\012\024\013\015\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\004\161\005\016\006\017\010\023\011\026\012\024\013" +
    "\015\001\001\000\016\005\036\006\017\010\023\011\026" +
    "\012\024\013\015\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    public void syntax_error(Symbol s){ this.s = s; }
    public Symbol getS(){ return this.s; }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // SENTENCIA_FOR ::= For Parentesis_a Identificador Igual Numero P_coma EXPRESION_A P_coma Identificador Op_incremento Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_FOR",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-13)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // SENTENCIA_DO_WHILE ::= Do Llave_a LISTA_SENTENCIAS Llave_c While Parentesis_a EXPRESION_A Parentesis_c P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_DO_WHILE",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // SENTENCIA_WHILE ::= While Parentesis_a EXPRESION_A Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_WHILE",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // SENTENCIA_IF ::= If Parentesis_a EXPRESION_A Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c Else Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-10)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // SENTENCIA_IF ::= If Parentesis_a EXPRESION_A Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DECLARACION ::= T_float Identificador P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DECLARACION ::= T_string Identificador Igual Texto P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararCadena(id, val); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DECLARACION ::= T_int Identificador Igual EXPRESION_A P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		 
        GeneradorEnsamblador.instancia.declararVariable(id);
        GeneradorEnsamblador.instancia.asignarDesdePila(id);
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // DECLARACION ::= T_int Identificador P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 GeneradorEnsamblador.instancia.declararVariable(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXPRESION_A ::= Numero 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 GeneradorEnsamblador.instancia.cargarValorEnPila(num); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EXPRESION_A ::= Identificador 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 GeneradorEnsamblador.instancia.cargarValorEnPila(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // EXPRESION_A ::= Parentesis_a EXPRESION_A Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EXPRESION_A ::= EXPRESION_A Division EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("/"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // EXPRESION_A ::= EXPRESION_A Multiplicacion EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("*"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // EXPRESION_A ::= EXPRESION_A Resta EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("-"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // EXPRESION_A ::= EXPRESION_A Suma EXPRESION_A 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.operacionPila("+"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_A",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= Retorno P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= Break P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= Limpia P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= Identificador Igual EXPRESION_A P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		 GeneradorEnsamblador.instancia.asignarDesdePila(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= Imprime Parentesis_a Identificador Parentesis_c P_coma 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 GeneradorEnsamblador.instancia.imprimirVariable(id); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= SENTENCIA_FOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= SENTENCIA_DO_WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= SENTENCIA_WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= SENTENCIA_IF 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LISTA_SENTENCIAS ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= T_void Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.generarPie(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.generarPie(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= T_int Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              Object RESULT =null;
		 GeneradorEnsamblador.instancia.generarPie(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

