
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 02 01:08:41 GMT-06:00 2025
//----------------------------------------------------

package micompiladorvpr.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int Lectura = 37;
  public static final int Llave_c = 26;
  public static final int Op_booleano = 22;
  public static final int Llave_a = 25;
  public static final int If = 8;
  public static final int T_dato = 5;
  public static final int nulo = 41;
  public static final int Else = 9;
  public static final int Corchete_c = 28;
  public static final int Hashtag = 42;
  public static final int Corchete_a = 27;
  public static final int Punto = 35;
  public static final int While = 11;
  public static final int Division = 17;
  public static final int Int = 6;
  public static final int Cadena = 7;
  public static final int Parentesis_c = 24;
  public static final int Parentesis_a = 23;
  public static final int For = 12;
  public static final int EOF = 0;
  public static final int P_coma = 30;
  public static final int LC = 34;
  public static final int error = 1;
  public static final int Puntos = 33;
  public static final int LEntrada_Salida = 44;
  public static final int Linea = 2;
  public static final int Ilibrerias = 43;
  public static final int Op_atribucion = 20;
  public static final int ERROR = 45;
  public static final int Do = 10;
  public static final int cas = 32;
  public static final int Op_logico = 18;
  public static final int saltoL = 3;
  public static final int formatoE = 39;
  public static final int formatoC = 40;
  public static final int Imprime = 36;
  public static final int Identificador = 46;
  public static final int Resta = 15;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 21;
  public static final int Numero = 47;
  public static final int Suma = 14;
  public static final int brek = 31;
  public static final int Main = 29;
  public static final int retorno = 38;
  public static final int Igual = 13;
  public static final int Comillas = 4;
}

