
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 02 16:04:09 GMT-06:00 2025
//----------------------------------------------------

package micompiladorvpr.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 39;
  public static final int Coma = 50;
  public static final int Lectura = 23;
  public static final int Llave_c = 45;
  public static final int Op_booleano = 41;
  public static final int Llave_a = 44;
  public static final int T_string = 6;
  public static final int ImprimeLn = 22;
  public static final int If = 10;
  public static final int T_char = 7;
  public static final int F_sin = 28;
  public static final int Potencia = 36;
  public static final int Default = 17;
  public static final int Else = 11;
  public static final int Break = 18;
  public static final int Corchete_c = 47;
  public static final int Hashtag = 52;
  public static final int Corchete_a = 46;
  public static final int Punto = 51;
  public static final int T_bool = 8;
  public static final int F_pow = 25;
  public static final int F_abs = 27;
  public static final int While = 13;
  public static final int Division = 34;
  public static final int Parentesis_c = 43;
  public static final int Modulo = 35;
  public static final int Parentesis_a = 42;
  public static final int For = 14;
  public static final int P_coma = 48;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 15;
  public static final int Texto = 58;
  public static final int LEntrada_Salida = 54;
  public static final int Linea = 2;
  public static final int Ilibrerias = 53;
  public static final int Op_atribucion = 40;
  public static final int T_void = 9;
  public static final int ERROR = 55;
  public static final int Do = 12;
  public static final int Op_logico = 37;
  public static final int Case = 16;
  public static final int Dos_puntos = 49;
  public static final int T_int = 4;
  public static final int Imprime = 21;
  public static final int Identificador = 56;
  public static final int F_sqrt = 26;
  public static final int Resta = 32;
  public static final int Multiplicacion = 33;
  public static final int Retorno = 20;
  public static final int Op_incremento = 38;
  public static final int Numero = 57;
  public static final int Suma = 31;
  public static final int T_float = 5;
  public static final int F_cos = 29;
  public static final int Main = 19;
  public static final int Igual = 30;
  public static final int Limpia = 24;
  public static final int Comillas = 3;
}

