
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 02 19:29:09 GMT-06:00 2025
//----------------------------------------------------

package micompiladorvpr.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 32;
  public static final int Coma = 43;
  public static final int Lectura = 23;
  public static final int Llave_c = 38;
  public static final int Op_booleano = 34;
  public static final int Llave_a = 37;
  public static final int T_string = 6;
  public static final int ImprimeLn = 22;
  public static final int If = 10;
  public static final int T_char = 7;
  public static final int Default = 19;
  public static final int Else = 11;
  public static final int Break = 20;
  public static final int Corchete_c = 40;
  public static final int Hashtag = 45;
  public static final int Corchete_a = 39;
  public static final int Punto = 44;
  public static final int T_bool = 8;
  public static final int While = 13;
  public static final int Division = 29;
  public static final int Parentesis_c = 36;
  public static final int Parentesis_a = 35;
  public static final int For = 14;
  public static final int P_coma = 41;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 17;
  public static final int Texto = 51;
  public static final int LEntrada_Salida = 47;
  public static final int Linea = 2;
  public static final int Ilibrerias = 46;
  public static final int Op_atribucion = 33;
  public static final int T_void = 9;
  public static final int ERROR = 48;
  public static final int Do = 12;
  public static final int Op_logico = 30;
  public static final int Case = 18;
  public static final int Dos_puntos = 42;
  public static final int T_int = 4;
  public static final int Imprime = 21;
  public static final int Identificador = 49;
  public static final int Resta = 27;
  public static final int Multiplicacion = 28;
  public static final int Retorno = 16;
  public static final int Op_incremento = 31;
  public static final int Numero = 50;
  public static final int Suma = 26;
  public static final int T_float = 5;
  public static final int Main = 15;
  public static final int Igual = 25;
  public static final int Limpia = 24;
  public static final int Comillas = 3;
}

